### ISSUE TITLE
SIM: Select Reconstruction algorithm

### ISSUE THREAD

**Issue by ranranking** [openUC2/ImSwitch#43]
Add gui element to select reconstruction algorithm
Either choose the napari-sim or the MCSIM from @ptbrown1729 from https://github.com/QI2lab/mcSIM

**Comment by ranranking** [comment]
cc: @beniroquai

**Comment by beniroquai** [comment]
You can now select napari or mcsim
<img width="371" alt="image" src="https://user-images.githubusercontent.com/4345528/224482492-5aab09ce-223f-4e7c-941f-c60f98ede85e.png">

**Comment by beniroquai** [comment]
@ranranking please check if it works properly
