### ISSUE TITLE
Supply important SIM parameters in gui

### ISSUE THREAD

**Issue by ranranking** [openUC2/ImSwitch#46]
Please list the following parameters used by the algorithm in the GUI:
- 

Thanks @beniroquai

**Comment by beniroquai** [comment]
This should be done now. Can you please check if it works as expected?

<img width="626" alt="image" src="https://user-images.githubusercontent.com/4345528/224482330-d672377d-3d7e-4724-a5bb-917dd0e33ec8.png">
