### ISSUE TITLE
SIM button switching widefield / reconstruction live view

### ISSUE THREAD

**Issue by ranranking** [openUC2/ImSwitch#51]
Do you think it make sense that we can switch the live view between widefield and reconstruction? @beniroquai

**Comment by beniroquai** [comment]
What do you mean? Have a toggle-switch that either displays the sum or the SR image? Should be possible, right now both are getting displayed as different layers, so you should be able to select/deselect them. They won't have the right scaling (e.g. 2x vs. 1x). In terms of laziness, I would prefer to keep it like that and perhaps upscale the widefield for better comparison/overlay? :)
