### ISSUE TITLE
Positioner widget issue

### ISSUE THREAD

**Issue by wwinnerhoo** [openUC2/ImSwitch#54]
Hi,

After upgrading to the latest version of ImSwitch ('$ pip install —upgrade imswitch', version 2.0.0), I can't move x y or z in the positioner widget by clicking related "+" or "--" button.  The reported message is below:

![image](https://github.com/openUC2/ImSwitch/assets/51831052/14bc7a13-6c99-40d3-8447-f5bce528cf1e)

The code around the line of " if axis == "X": speed = self.speed["X"]" in ESP32StageManager.py are:

![image](https://github.com/openUC2/ImSwitch/assets/51831052/83735280-9655-478d-a273-961b2e952966)

Hopefully, it is sufficient to help me to solve this issue. Thanks in advance!

Kinds,
Yuhao

**Comment by beniroquai** [comment]
Has been fixed. Sorry for the late reply.
